### ISSUE TITLE
Fixing the "About Us" and "Contact" buttons

### ISSUE THREAD

**Issue by LucaSain** [Bytecrowds/bytecrowds#1]
#### This happens becuase of the way the button is instantiated. It is more of a button with an *a href* on top than a regular button.
![Screen Shot 2022-09-10 at 22 28 57](https://user-images.githubusercontent.com/75369190/189498971-1245bb58-8d30-4ba3-b273-92ffd7c73262.png)

**Comment by TudorZgimbau** [comment]
Thanks for pointing out. Fixed by https://github.com/Bytecrowds/frontend/commit/46a5cda1ecf14a6b7eabfcab9af347334b419eba
